# -*- mode: ruby -*-
# vi: set ft=ruby :
# 
# Needed plugins:
# - vagrant-libvirt
# - vagrant-winrm
#

name = "ToggleAudioTrayIcon"
title = "win-" + name

Vagrant.configure("2") do |config|

  config.vm.define title

  config.vm.hostname = title

  config.vm.box = "peru/windows-10-enterprise-x64-eval"

  config.winssh.shell = "powershell"

  config.vm.provider :libvirt do |domain|
    domain.memory = 4096
    domain.cpus = 4
    domain.nested = true
    domain.storage_pool_name = "vm"
    domain.title = title

    # Add an additional sound device using qemu. It will not show up in virt-manager though.
    domain.qemuargs :value => "-device"
    domain.qemuargs :value => "intel-hda,bus=pci.0,addr=0x1b"
    domain.qemuargs :value => "-device"
    domain.qemuargs :value => "hda-micro,audiodev=hda"
    domain.qemuargs :value => "-audiodev"
    domain.qemuargs :value => "pa,id=hda,server=/run/user/1000/pulse/native"

  end

  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  # Make sure that the ssh_config is not left around after destroy
  config.trigger.after :destroy do |trigger|
    trigger.run = { inline: "rm -Rf ssh_config" }
  end

end
